### ISSUE TITLE
Manual code point entry for Chinese fonts.

### ISSUE THREAD

**Issue by Remunerator** [Pconti31/TTF2GFX#10]
I have a font with Chinese characters which take up a substantial unicode range, and I'm unable to scroll past a certain point (around `0x3e5b`). A ton of characters are displayed, which leads to huge memory consumption as well.

As you can see in the screenshot below, I'm unable to add certain characters which are past `0x4000`. Manual search doesn't help either as the scroll bar can't exceed that point. Would be good if you could allow me to manually enter the code point (or better still, a list of code points) of the character I want to add to the list on the left.

![image](https://user-images.githubusercontent.com/75004710/228298498-a64a4a7b-1eb2-45fc-8c39-c85005891022.png)

**Comment by Pconti31** [comment]
@Remunerator Happy to try.  Any chance you could post a zip file of your font for me to test against.
Also what code points you want to try to avoid needing to scroll.
Paul--

**Comment by Pconti31** [comment]
@Remunerator Would a "go to Unicode xxxxx" field be better or would it be in addition?
I also like the idea of a say, right click on a field then allow you to enter a Unicode directly.
What do you think?
Paul--

**Comment by Pconti31** [comment]
@Remunerator Ok, I created a bug fix as Release 2.02.
Turns out that I already had a go to Unicode but called it Search so I renamed it to "Go To Unicode" to clear that up.  The scroll issue was due to too small a number for scroll area.  It was 7500 now its 100,000.
Paul--

**Comment by Remunerator** [comment]
Many thanks for the quick response Paul, and amazing work. I'll close the issue, but for your reference, I've attached the font I was trying this out with in case you'd like to try as well
[OPPOSans-R.zip](https://github.com/Pconti31/TTF2GFX/files/11135627/OPPOSans-R.zip)
