### ISSUE TITLE
Missing code points per row

### ISSUE THREAD

**Issue by Remunerator** [Pconti31/TTF2GFX#12]
Hi again Paul, it seems like each row on the right table is missing 2 code points at the end. For instance, in the screenshot attached, the code point for "M" (`0x004d`) is followed by the one for "P" (`0x0050`) on the next row. The code points for "N" (`0x004e`) and "O" (`0x004f`) are skipped, and this issue also occurs on the other rows. Maximising the window doesn't seem to make a difference.

On the left table, you can see that "N" and "O" are valid characters in the font, so it's not the case that the font is missing those characters.

Manually searching with the "Go to unicode" function does not work either; it scrolls to where the code point is supposed to be, but the requested cell is not visible.

-- Rem
![Screenshot 2023-04-03 222440](https://user-images.githubusercontent.com/75004710/229538978-9f253d0d-b426-4373-a855-c5968a5610ea.png)

**Comment by Pconti31** [comment]
@Remunerator Hmmm, well thanks for pointing this out and for posting your font.
I'll take a look and see what is going on.  
Paul--

**Comment by Remunerator** [comment]
Perfect, thank you so much!
